apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kazooui
spec:
  replicas: 1
  template:
    metadata:
      name: kazooui
      labels:
        app: kazooui
        project: valuphone
        environment: production
    spec:
      containers:
        - name: kazooui
          image: callforamerica/kazooui
          env:
            - name: HTTPD_LOG_LEVEL
              value: error
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 1G 
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 15
          imagePullPolicy: Always
      restartPolicy: Always
