apiVersion: v1
kind: ReplicationController
metadata:
  name: kazooui
  labels:
    app: kazooui
    project: valuphone
    role: user-interface
spec:
  replicas: 1
  selector:
    app: kazooui
    project: valuphone
  template:
    metadata:
      name: kazooui
      labels:
        app: kazooui
        project: valuphone
    spec:
      containers:
        - name: kazooui
          image: callforamerica/kazooui
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 1G 
          readinessProbe:
            httpGet:
              path: /kazoo-ui
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /kazoo-ui
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 3
      restartPolicy: Always