kind: Service
apiVersion: v1
metadata: 
  name: kazooui
spec:
  selector:
    app: kazooui
    project: valuphone
    environment: production
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
